---
# Template configuration files for nginx

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ nginx_templates_copy }}"
  when: nginx_copy_templates
